import setuptools


with open("README.md", "r") as txt:
    long_description = txt.read()

setuptools.setup(
    name="wibuapi",
    version="0.1.3",
    description="Official Python Wrapper for Wibu API.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    license="GNU Lesser General Public License v3 (LGPLv3)",
    author="Yoga Pranata",
    author_email="yoga@zyxdevs.eu.org",
    url="https://github.com/zYxDevs/wibu-api-py",
    packages=setuptools.find_packages(),
    keywords=[
        "wibu",
        "weebs",
        "otaku",
        "anime",
        "hentai",
        "donghua",
        "manga",
        "doujin",
        "manhwa",
        "manhua",
        "jdrama",
        "jav",
        "music",
        "booru",
        "api",
        "nsfw",
        "scraper",
        "bypasser",
        "genshin",
        "facebook",
        "youtube",
    ],
    classifiers=[
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
        "Development Status :: 5 - Production/Stable",
        "Natural Language :: English",
        "Topic :: Internet",
        "Topic :: Software Development :: Libraries",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    ],
    install_requires=["requests"],
    python_requires=">=3.6",
)
